### ISSUE TITLE
按照说明安装完毕后运行报错

### ISSUE THREAD

**Issue by meltifa** [callmez/egg-generator#1]
先是
Can not find plugin egg-generator
安装egg-generator后可以运行，但是添加数据又报错
ERROR 9916 [-/127.0.0.1/-/20ms POST /generator/crud] nodejs.TypeError: model.getQueryInterface is not a function

**Comment by callmez** [comment]
报下 egg-generator的版本和egg-sequelize的版本

**Comment by meltifa** [comment]
egg-generator 1.1.3
egg-isequelize 2.0.0-beta.3

**Comment by callmez** [comment]
这个代码是没有问题的.因为我现在就是在跑这个
你可以看
egg-generator/app/service/generator/Crud.js#28行
egg-isequelize/lib/modelLoader#22行
都做了兼容
